### ISSUE TITLE
New npm start script fails

### ISSUE THREAD

**Issue by mmozuras** [max-mapper/voxel-hello-world#16]
New npm start script (0ff500d3d150152adfbc0f77207c225a5a00f35f) fails. npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/0.10.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@1.2.14
3 info using node@v0.10.0
4 verbose read json /Users/mindaugasmozuras/long path to project/package.json
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart voxel-hello-world@0.0.6
7 info start voxel-hello-world@0.0.6
8 verbose unsafe-perm in lifecycle true
9 silly exec sh "-c" "browservefy test.js:bundle.js 8080 -- -d"
10 silly sh,-c,browservefy test.js:bundle.js 8080 -- -d,/Users/mindaugasmozuras/long path to project spawning
11 info voxel-hello-world@0.0.6 Failed to exec start script
12 error voxel-hello-world@0.0.6 start: `browservefy test.js:bundle.js 8080 -- -d`
12 error `sh "-c" "browservefy test.js:bundle.js 8080 -- -d"` failed with 8
13 error Failed at the voxel-hello-world@0.0.6 start script.
13 error This is most likely a problem with the voxel-hello-world package,
```

Old one works fine.

**Comment by max-mapper** [comment]
hmm I wonder what 'failed with 8' means. I'm installing 0.10.0 to try and reproduce. Can I ask what OS you are running?

**Comment by mmozuras** [comment]
Of course - Mac OSX Mountain Lion

**Comment by max-mapper** [comment]
Ahh -- reproduced

```
pizzacats:voxel-hello-world maxogden$ npm start

> voxel-hello-world@0.0.6 start /Users/maxogden/Desktop/voxel-hello-world
> browservefy test.js:bundle.js 8080 -- -d


path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at which_browserify (/Users/maxogden/Desktop/voxel-hello-world/node_modules/browservefy/index.js:182:20)
    at Object.<anonymous> (/Users/maxogden/Desktop/voxel-hello-world/node_modules/browservefy/index.js:18:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/maxogden/Desktop/voxel-hello-world/node_modules/browservefy/bin/browservefy:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:903:3
npm ERR! voxel-hello-world@0.0.6 start: `browservefy test.js:bundle.js 8080 -- -d`
npm ERR! `sh "-c" "browservefy test.js:bundle.js 8080 -- -d"` failed with 8
npm ERR! 
npm ERR! Failed at the voxel-hello-world@0.0.6 start script.
npm ERR! This is most likely a problem with the voxel-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browservefy test.js:bundle.js 8080 -- -d
npm ERR! You can get their info via:
npm ERR!     npm owner ls voxel-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 11.4.2
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/maxogden/Desktop/voxel-hello-world
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/maxogden/Desktop/voxel-hello-world/npm-debug.log
npm ERR! not ok code 0

```

**Comment by max-mapper** [comment]
@mmozuras I think I have a fix, can you try doing `npm install browservefy@0.0.9` and trying `npm start` again?

**Comment by mmozuras** [comment]
Works fine :+1:
