### ISSUE TITLE
It doesn't do anything

### ISSUE THREAD

**Issue by charliecalvert** [max-mapper/voxel-hello-world#21]
I run npm start, I browse to Port 8080. I get the logo, I get the cross hair, I get nothing else. Chrome debugger shows bundle.js as an empty, blank file. If this is what is expected, what are the next steps?

**Comment by max-mapper** [comment]
I just tested and it works for me. I have node v0.1.0. here is the output from my terminal:

```
Desktop maxogden$ git clone git@github.com:maxogden/voxel-hello-world.git
Cloning into 'voxel-hello-world'...
remote: Counting objects: 232, done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 232 (delta 135), reused 212 (delta 118)
Receiving objects: 100% (232/232), 747.55 KiB | 323 KiB/s, done.
Resolving deltas: 100% (135/135), done.
pizzacats:Desktop maxogden$ cd voxel-hello-world/
pizzacats:voxel-hello-world maxogden$ npm install
npm http GET https://registry.npmjs.org/voxel-highlight/0.0.8
npm http GET https://registry.npmjs.org/extend/1.1.3
npm http GET https://registry.npmjs.org/browserify/1.17.3
npm http GET https://registry.npmjs.org/voxel-player/0.1.0
npm http GET https://registry.npmjs.org/browservefy/0.0.9
npm http GET https://registry.npmjs.org/voxel/0.3.1
npm http GET https://registry.npmjs.org/painterly-textures/0.0.3
npm http GET https://registry.npmjs.org/toolbar/0.0.5
npm http GET https://registry.npmjs.org/voxel-engine
npm http 304 https://registry.npmjs.org/voxel-highlight/0.0.8
npm http 304 https://registry.npmjs.org/voxel-player/0.1.0
npm http 200 https://registry.npmjs.org/browservefy/0.0.9
npm http GET https://registry.npmjs.org/browservefy/-/browservefy-0.0.9.tgz
npm http 304 https://registry.npmjs.org/extend/1.1.3
npm http 200 https://registry.npmjs.org/browserify/1.17.3
npm http GET https://registry.npmjs.org/browserify/-/browserify-1.17.3.tgz
npm http 304 https://registry.npmjs.org/voxel/0.3.1
npm http 304 https://registry.npmjs.org/toolbar/0.0.5
npm http 304 https://registry.npmjs.org/painterly-textures/0.0.3
npm http 304 https://registry.npmjs.org/voxel-engine
npm http 200 https://registry.npmjs.org/browservefy/-/browservefy-0.0.9.tgz
npm http 200 https://registry.npmjs.org/browserify/-/browserify-1.17.3.tgz
npm http GET https://registry.npmjs.org/underscore/1.4.3
npm http GET https://registry.npmjs.org/inherits/1.0.0
npm http GET https://registry.npmjs.org/through
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/live-reload
npm http GET https://registry.npmjs.org/response-stream/0.0.0
npm http GET https://registry.npmjs.org/filed/0.0.7
npm http GET https://registry.npmjs.org/minecraft-skin
npm http GET https://registry.npmjs.org/voxel-chunks/0.0.2
npm http GET https://registry.npmjs.org/voxel-raycast/0.2.1
npm http GET https://registry.npmjs.org/voxel-control/0.0.7
npm http GET https://registry.npmjs.org/voxel-texture/0.4.0
npm http GET https://registry.npmjs.org/voxel-region-change/0.1.0
npm http GET https://registry.npmjs.org/voxel-physical/0.0.8
npm http GET https://registry.npmjs.org/three/0.56.0
npm http GET https://registry.npmjs.org/aabb-3d/0.0.0
npm http GET https://registry.npmjs.org/interact/0.0.2
npm http GET https://registry.npmjs.org/gl-matrix/2.0.0
npm http GET https://registry.npmjs.org/kb-controls/0.0.2
npm http GET https://registry.npmjs.org/pin-it/0.0.1
npm http GET https://registry.npmjs.org/raf/0.0.1
npm http GET https://registry.npmjs.org/spatial-events/0.0.1
npm http GET https://registry.npmjs.org/spatial-trigger/0.0.0
npm http GET https://registry.npmjs.org/collide-3d-tilemap/0.0.1
npm http GET https://registry.npmjs.org/voxel-mesh/0.2.1
npm http GET https://registry.npmjs.org/voxel-view/0.0.6
npm http GET https://registry.npmjs.org/element-class/0.0.2
npm http 304 https://registry.npmjs.org/underscore/1.4.3
npm http 304 https://registry.npmjs.org/inherits/1.0.0
npm http 304 https://registry.npmjs.org/through
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/live-reload
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/filed/0.0.7
npm http 304 https://registry.npmjs.org/response-stream/0.0.0
npm http 304 https://registry.npmjs.org/minecraft-skin
npm http 304 https://registry.npmjs.org/voxel-chunks/0.0.2
npm http 304 https://registry.npmjs.org/voxel-raycast/0.2.1
npm http 304 https://registry.npmjs.org/voxel-control/0.0.7
npm http 304 https://registry.npmjs.org/voxel-texture/0.4.0
npm http GET https://registry.npmjs.org/watchr
npm http GET https://registry.npmjs.org/browserify-server
npm http GET https://registry.npmjs.org/shoe/0.0.5
npm http GET https://registry.npmjs.org/hound
npm http 304 https://registry.npmjs.org/voxel-physical/0.0.8
npm http GET https://registry.npmjs.org/reconnect
npm http 304 https://registry.npmjs.org/voxel-region-change/0.1.0
npm http 304 https://registry.npmjs.org/aabb-3d/0.0.0
npm http 304 https://registry.npmjs.org/three/0.56.0
npm http 304 https://registry.npmjs.org/interact/0.0.2
npm http 304 https://registry.npmjs.org/gl-matrix/2.0.0
npm http 304 https://registry.npmjs.org/kb-controls/0.0.2
npm http 304 https://registry.npmjs.org/pin-it/0.0.1
npm http 304 https://registry.npmjs.org/raf/0.0.1
npm http 304 https://registry.npmjs.org/spatial-events/0.0.1
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/spatial-trigger/0.0.0
npm http 304 https://registry.npmjs.org/collide-3d-tilemap/0.0.1
npm http 304 https://registry.npmjs.org/voxel-mesh/0.2.1
npm http 304 https://registry.npmjs.org/voxel-view/0.0.6
npm http 304 https://registry.npmjs.org/element-class/0.0.2
npm http 304 https://registry.npmjs.org/browserify-server
npm http 304 https://registry.npmjs.org/shoe/0.0.5
npm http 304 https://registry.npmjs.org/hound
npm http GET https://registry.npmjs.org/syntax-error
npm http GET https://registry.npmjs.org/resolve
npm http GET https://registry.npmjs.org/nub
npm http GET https://registry.npmjs.org/deputy
npm http GET https://registry.npmjs.org/commondir
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/http-browserify
npm http GET https://registry.npmjs.org/vm-browserify
npm http GET https://registry.npmjs.org/detective
npm http GET https://registry.npmjs.org/crypto-browserify
npm http GET https://registry.npmjs.org/buffer-browserify
npm http GET https://registry.npmjs.org/console-browserify
npm http 304 https://registry.npmjs.org/reconnect
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/nub
npm http 304 https://registry.npmjs.org/deputy
npm http 200 https://registry.npmjs.org/watchr
npm http 304 https://registry.npmjs.org/commondir
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/http-browserify
npm http 304 https://registry.npmjs.org/vm-browserify
npm http 304 https://registry.npmjs.org/detective
npm http 304 https://registry.npmjs.org/crypto-browserify
npm http 304 https://registry.npmjs.org/buffer-browserify
npm http 304 https://registry.npmjs.org/console-browserify
npm http 304 https://registry.npmjs.org/resolve
npm http 304 https://registry.npmjs.org/syntax-error
npm http GET https://registry.npmjs.org/vkey
npm http GET https://registry.npmjs.org/ever
npm http GET https://registry.npmjs.org/pointer-lock/0.0.3
npm http GET https://registry.npmjs.org/drag-stream/0.0.2
npm http GET https://registry.npmjs.org/fullscreen/0.0.1
npm http GET https://registry.npmjs.org/voxel-mesh
npm http GET https://registry.npmjs.org/voxel
npm http GET https://registry.npmjs.org/ecstatic
npm http GET https://registry.npmjs.org/browserify
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/bal-util
npm http 304 https://registry.npmjs.org/vkey
npm http 304 https://registry.npmjs.org/ever
npm http GET https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/base64-js/0.0.2
npm http 304 https://registry.npmjs.org/pointer-lock/0.0.3
npm http 304 https://registry.npmjs.org/fullscreen/0.0.1
npm http 304 https://registry.npmjs.org/drag-stream/0.0.2
npm http 304 https://registry.npmjs.org/voxel-mesh
npm http 304 https://registry.npmjs.org/voxel
npm http 304 https://registry.npmjs.org/browserify
npm http 304 https://registry.npmjs.org/ecstatic
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/base64-js/0.0.2
npm http GET https://registry.npmjs.org/domnode-dom
npm http GET https://registry.npmjs.org/three/0.54.0
npm http GET https://registry.npmjs.org/shoe
npm http GET https://registry.npmjs.org/backoff
npm http GET https://registry.npmjs.org/h
npm http 200 https://registry.npmjs.org/bal-util
npm http GET https://registry.npmjs.org/sockjs-windows
npm http 304 https://registry.npmjs.org/h
npm http 304 https://registry.npmjs.org/domnode-dom
npm http 304 https://registry.npmjs.org/sockjs-windows
npm http 304 https://registry.npmjs.org/three/0.54.0
npm http 304 https://registry.npmjs.org/backoff
npm http 304 https://registry.npmjs.org/shoe
npm http GET https://registry.npmjs.org/opaque/0.0.1
npm http GET https://registry.npmjs.org/mime/1.2.5
npm http GET https://registry.npmjs.org/ent
npm http GET https://registry.npmjs.org/domnode
npm http 304 https://registry.npmjs.org/opaque/0.0.1
npm http GET https://registry.npmjs.org/concat-stream/0.0.8
npm http 304 https://registry.npmjs.org/mime/1.2.5
npm http 304 https://registry.npmjs.org/ent
npm http 304 https://registry.npmjs.org/domnode
npm http 304 https://registry.npmjs.org/concat-stream/0.0.8
npm http GET https://registry.npmjs.org/mustache/0.4.0
npm http 304 https://registry.npmjs.org/mustache/0.4.0
npm WARN package.json mustache@0.4.0 No README.md file found!
npm http GET https://registry.npmjs.org/node-uuid/1.3.3
npm http GET https://registry.npmjs.org/faye-websocket/0.4.0
npm http 304 https://registry.npmjs.org/faye-websocket/0.4.0
npm http 304 https://registry.npmjs.org/node-uuid/1.3.3
npm http GET https://registry.npmjs.org/node-uuid/1.3.3
npm http GET https://registry.npmjs.org/faye-websocket/0.4.0
npm http GET https://registry.npmjs.org/rbytes/0.0.2
npm http 304 https://registry.npmjs.org/node-uuid/1.3.3
npm http 304 https://registry.npmjs.org/faye-websocket/0.4.0
npm http 304 https://registry.npmjs.org/rbytes/0.0.2

> rbytes@0.0.2 install /Users/maxogden/Desktop/voxel-hello-world/node_modules/browservefy/node_modules/live-reload/node_modules/reconnect/node_modules/shoe/node_modules/sockjs/node_modules/rbytes
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /usr/local/lib/node_modules 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.269s)
Waf: Entering directory `/Users/maxogden/Desktop/voxel-hello-world/node_modules/browservefy/node_modules/live-reload/node_modules/reconnect/node_modules/shoe/node_modules/sockjs/node_modules/rbytes/build'
[1/2] cxx: src/binding.cc -> build/Release/src/binding_1.o
../src/binding.cc: In function ‘v8::Handle<v8::Value> RandBytes(const v8::Arguments&)’:
../src/binding.cc:36: warning: ‘RAND_bytes’ is deprecated (declared at /usr/include/openssl/rand.h:104)
../src/binding.cc:36: warning: ‘RAND_bytes’ is deprecated (declared at /usr/include/openssl/rand.h:104)
../src/binding.cc:41: warning: ‘ERR_get_error’ is deprecated (declared at /usr/include/openssl/err.h:266)
../src/binding.cc:41: warning: ‘ERR_get_error’ is deprecated (declared at /usr/include/openssl/err.h:266)
../src/binding.cc:43: warning: ‘ERR_error_string’ is deprecated (declared at /usr/include/openssl/err.h:279)
../src/binding.cc:43: warning: ‘ERR_error_string’ is deprecated (declared at /usr/include/openssl/err.h:279)
[2/2] cxx_link: build/Release/src/binding_1.o -> build/Release/binding.node
Waf: Leaving directory `/Users/maxogden/Desktop/voxel-hello-world/node_modules/browservefy/node_modules/live-reload/node_modules/reconnect/node_modules/shoe/node_modules/sockjs/node_modules/rbytes/build'
'build' finished successfully (0.907s)
npm WARN prefer global browservefy@0.0.9 should be installed with -g
extend@1.1.3 node_modules/extend

painterly-textures@0.0.3 node_modules/painterly-textures

voxel@0.3.1 node_modules/voxel
└── inherits@1.0.0

voxel-player@0.1.0 node_modules/voxel-player
└── minecraft-skin@0.1.2

voxel-highlight@0.0.8 node_modules/voxel-highlight
├── inherits@1.0.0
└── underscore@1.4.3

toolbar@0.0.5 node_modules/toolbar
├── element-class@0.0.2
└── inherits@1.0.0

voxel-engine@0.16.3 node_modules/voxel-engine
├── voxel-view@0.0.6
├── inherits@1.0.0
├── pin-it@0.0.1
├── collide-3d-tilemap@0.0.1
├── raf@0.0.1
├── spatial-trigger@0.0.0
├── aabb-3d@0.0.0
├── voxel-control@0.0.7
├── voxel-physical@0.0.8
├── voxel-mesh@0.2.1
├── spatial-events@0.0.1
├── voxel-region-change@0.1.0
├── voxel-raycast@0.2.1
├── kb-controls@0.0.2 (vkey@0.0.2, ever@0.0.3)
├── gl-matrix@2.0.0
├── voxel-texture@0.4.0 (opaque@0.0.1)
├── three@0.56.0
├── voxel-chunks@0.0.2 (voxel@0.1.5, voxel-mesh@0.1.1)
└── interact@0.0.2 (fullscreen@0.0.1, pointer-lock@0.0.3, drag-stream@0.0.2)

browserify@1.17.3 node_modules/browserify
├── nub@0.0.0
├── commondir@0.0.1
├── console-browserify@0.1.6
├── vm-browserify@0.0.1
├── crypto-browserify@0.2.1
├── resolve@0.2.8
├── buffer-browserify@0.0.5 (base64-js@0.0.2)
├── optimist@0.3.7 (wordwrap@0.0.2)
├── deputy@0.0.4 (mkdirp@0.3.5)
├── coffee-script@1.6.2
├── http-browserify@0.1.11 (concat-stream@0.0.8)
├── syntax-error@0.0.0 (esprima@0.9.9)
└── detective@0.2.1 (esprima@0.9.9)

browservefy@0.0.9 node_modules/browservefy
├── colors@0.6.0-1
├── through@2.2.7
├── response-stream@0.0.0
├── filed@0.0.7
├── optimist@0.3.7 (wordwrap@0.0.2)
└── live-reload@0.2.0 (hound@1.0.4, watchr@2.1.6, shoe@0.0.5, browserify-server@2.0.4, reconnect@0.1.5)
pizzacats:voxel-hello-world maxogden$ npm start

> voxel-hello-world@0.4.2 start /Users/maxogden/Desktop/voxel-hello-world
> browservefy test.js:bundle.js 8080 -- -d

listening on 8080
using ./node_modules/.bin/browserify
200    7ms    1.04KB /index.html
200    3ms    6.91KB /logo-white.png
200    2ms      882B /crosshair.png
200  796ms    2.25MB /bundle.js -> ./node_modules/.bin/browserify ./test.js -d
200    6ms    3.44KB /node_modules/painterly-textures/textures/grass_dirt.png
200    6ms    3.29KB /node_modules/painterly-textures/textures/grass.png
200    6ms    3.44KB /node_modules/painterly-textures/textures/dirt.png
200    5ms    3.41KB /node_modules/painterly-textures/textures/obsidian.png
200    3ms    3.45KB /node_modules/painterly-textures/textures/brick.png
200    2ms    3.06KB /node_modules/painterly-textures/textures/plank.png
200    1ms     3.9KB /player.png
200    2ms  147.63KB /favicon.ico
```

**Comment by charliecalvert** [comment]
Perhaps it's because I'm on Windows. I've upgraded to latest nodejs and get this:

G:\Src\Git\voxel-hello-world>npm start

> voxel-hello-world@0.4.2 start G:\Src\Git\voxel-hello-world
> browservefy test.js:bundle.js 8080 -- -d

listening on 8080
using .\node_modules.bin\browserify
200   18ms    1.04KB /index.html

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:977:11)
    at Process.ChildProcess._handle.onexit (child_process.js:768:34)
npm ERR! voxel-hello-world@0.4.2 start: `browservefy test.js:bundle.js 8080 --
 -d`
npm ERR! `cmd "/c" "browservefy test.js:bundle.js 8080 -- -d"` failed with 8

**Comment by max-mapper** [comment]
ah, one thing I noticed is that I am using an old version of something. browservefy is now called 'beefy'. I just updated and pushed an update, try pulling the newest code and trying `npm install` and `npm start` again

**Comment by charliecalvert** [comment]
I pulled down beefy, and now get this, with the error occurring when I try to access localhost:8080:

G:\Src\Git\voxel-hello-world>npm start

> voxel-hello-world@0.4.2 start G:\Src\Git\voxel-hello-world
> beefy test.js:bundle.js 8080

listening on 8080
using browserify
200   13ms    1.04KB /index.html

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:977:11)
    at Process.ChildProcess._handle.onexit (child_process.js:768:34)
npm ERR! voxel-hello-world@0.4.2 start: `beefy test.js:bundle.js 8080`
npm ERR! `cmd "/c" "beefy test.js:bundle.js 8080"` failed with 8
npm ERR!
npm ERR! Failed at the voxel-hello-world@0.4.2 start script.
npm ERR! This is most likely a problem with the voxel-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     beefy test.js:bundle.js 8080
npm ERR! You can get their info via:
npm ERR!     npm owner ls voxel-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\n
odejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! cwd G:\Src\Git\voxel-hello-world
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     G:\Src\Git\voxel-hello-world\npm-debug.log
npm ERR! not ok code 0

G:\Src\Git\voxel-hello-world>

**Comment by max-mapper** [comment]
hmmm... thanks for trying. beefy is maintained by @chrisdickinson, maybe
there is a bug with it on windows

**Comment by charliecalvert** [comment]
I'll let you know if I learn anything.

**Comment by charliecalvert** [comment]
Haven't really made any progress. It works fine on my Linux box, but I just don't see why it isn't working on Windows.

I come to this with no experience in this area, so trying to debug the code is just not getting me very far. I find the browserify code confusing. I want to be able to step through the projects, but it crashes before it loads in Chrome, so I don't see how to see a break point in this huge JavaScript file that seems to never really load on Windows.

**Comment by vladikoff** [comment]
This can probably be closed, I've tested [ArchiveRoom](http://archiveroom.net/) and a lot of other projects on Windows and it ran fine.

**Comment by shama** [comment]
This can be closed as support for windows was fixed in beefy here: chrisdickinson/beefy#11

**Comment by kumavis** [comment]
@charliecalvert did you get it working on your machine?
