### ISSUE TITLE
Seems to be broken?

### ISSUE THREAD

**Issue by z3t0** [max-mapper/voxel-hello-world#25]
I'm using windows

``` console
C:\Users\Rafi Khan\Desktop\voxel-hello-world-master>beefy -o
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Rafi Khan\Desktop\voxel-hello-world-master\n
ode_modules\browserify/bin/args.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupBrowserify (C:\Users\Rafi Khan\AppData\Roaming\npm\node_modules\beef
y\lib\bundlers\browserify.js:6:19)
    at onlocalbrowserify (C:\Users\Rafi Khan\AppData\Roaming\npm\node_modules\be
efy\lib\setup-bundlers.js:30:5)
    at C:\Users\Rafi Khan\AppData\Roaming\npm\node_modules\beefy\node_modules\re
solve\lib\async.js:42:21
    at C:\Users\Rafi Khan\AppData\Roaming\npm\node_modules\beefy\node_modules\re
solve\lib\async.js:121:35
    at C:\Users\Rafi Khan\AppData\Roaming\npm\node_modules\beefy\node_modules\re
solve\lib\async.js:93:39
    at C:\Users\Rafi Khan\AppData\Roaming\npm\node_modules\beefy\node_modules\re
solve\lib\async.js:59:30
```

**Comment by z3t0** [comment]
The hosted one also seems to be broken
http://maxogden.github.io/voxel-hello-world/

**Comment by alanszlosek** [comment]
Have you installed browserify (`npm install browserify`)? I encountered something similar and that fixed it.

**Comment by z3t0** [comment]
@alanszlosek yes, its odd because the one hosted is also broken. Don't worry about it I already managed to get this working (not this specific project though). However I will leave the issue open because it is still valid and will be helpful to anyone new who tries this.

**Comment by rickhenderson** [comment]
So to help others who are having the problem what did you do to fix it z3to0?

**Comment by z3t0** [comment]
@rickhenderson Hi, Sorry I didn't mention my "fix" because it is not really a fix. Instead I just used voxel-engine-stackgl
