### ISSUE TITLE
Some packages are not installed correctly or missing

### ISSUE THREAD

**Issue by simkuns** [max-mapper/voxel-hello-world#26]
**Step 1. Importing git repository**

```
git clone https://github.com/maxogden/voxel-hello-world.git
```

**Step 2. Do the first time setup**

```
cd voxel-hello-world
npm install
```

**Step 3. Run the start script**

```
npm start
```

This gives the output:

```
> voxel-hello-world@0.6.0 start C:\Users\homw\Documents\voxel-hello-world
> beefy test.js:bundle.js 8080

listening on 8080
using .\node_modules\.bin\browserify
```

When you open http://localhost:8080 you get the following error in console and in npm-debug.log

console:

```
200   13ms    1.08KB /index.html
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\homw\Documents\voxel-hello-world\node_modules\.bin\browser
ify ENOENT
  at exports._errnoException (util.js:870:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
  at onErrorNT (internal/child_process.js:344:16)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickCallback (node.js:356:17)


npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! voxel-hello-world@0.6.0 start: `beefy test.js:bundle.js 8080`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the voxel-hello-world@0.6.0 start script 'beefy test.js:bundl
e.js 8080'.
npm ERR! This is most likely a problem with the voxel-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     beefy test.js:bundle.js 8080
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs voxel-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls voxel-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\homw\Documents\voxel-hello-world\npm-debug.log
```

npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart voxel-hello-world@0.6.0
6 info start voxel-hello-world@0.6.0
7 verbose unsafe-perm in lifecycle true
8 info voxel-hello-world@0.6.0 Failed to exec start script
9 verbose stack Error: voxel-hello-world@0.6.0 start: `beefy test.js:bundle.js 8080`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid voxel-hello-world@0.6.0
11 verbose cwd C:\Users\homw\Documents\voxel-hello-world
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.0
15 error npm  v2.14.20
16 error code ELIFECYCLE
17 error voxel-hello-world@0.6.0 start: `beefy test.js:bundle.js 8080`
17 error Exit status 1
18 error Failed at the voxel-hello-world@0.6.0 start script 'beefy test.js:bundle.js 8080'.
18 error This is most likely a problem with the voxel-hello-world package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     beefy test.js:bundle.js 8080
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs voxel-hello-world
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls voxel-hello-world
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**However, I was able to fix this error by simply typing:**

```
npm install beefy
npm install browserify
npm start
```

**Comment by memoriasIT** [comment]
God bless you brother.
**For me to work I had to do:**

```
npm uninstall beefy
npm uninstall browserify

npm install beefy
npm install browswerify
npm install voxel-walk

npm start
```

**Comment by kumavis** [comment]
https://github.com/maxogden/voxel-hello-world/pull/27#issuecomment-1321603761
